/**
 * Nono Game - Card Decks
 * Each deck contains cards with a word and 5 taboo words that cannot be used
 */

const DECKS = {
    movies: {
        id: 'movies',
        name: 'Movies & TV',
        icon: '🎬',
        cards: [
            { word: 'Harry Potter', taboo: ['Wizard', 'Magic', 'Hogwarts', 'Wand', 'Voldemort'] },
            { word: 'Titanic', taboo: ['Ship', 'Sink', 'Iceberg', 'Rose', 'Jack'] },
            { word: 'Star Wars', taboo: ['Space', 'Jedi', 'Force', 'Lightsaber', 'Darth Vader'] },
            { word: 'The Lion King', taboo: ['Simba', 'Africa', 'Mufasa', 'Jungle', 'Disney'] },
            { word: 'Friends', taboo: ['Sitcom', 'Rachel', 'Central Perk', 'New York', 'Apartment'] },
            { word: 'Avatar', taboo: ['Blue', 'Alien', 'Pandora', 'James Cameron', '3D'] },
            { word: 'Breaking Bad', taboo: ['Meth', 'Chemistry', 'Walter', 'Teacher', 'Drug'] },
            { word: 'The Office', taboo: ['Michael Scott', 'Dunder', 'Paper', 'Scranton', 'Boss'] },
            { word: 'Frozen', taboo: ['Elsa', 'Ice', 'Snow', 'Let It Go', 'Anna'] },
            { word: 'Game of Thrones', taboo: ['Dragon', 'Winter', 'Throne', 'King', 'Westeros'] },
            { word: 'Jurassic Park', taboo: ['Dinosaur', 'T-Rex', 'Island', 'Spielberg', 'DNA'] },
            { word: 'The Godfather', taboo: ['Mafia', 'Italian', 'Family', 'Corleone', 'Offer'] },
            { word: 'Stranger Things', taboo: ['Eleven', 'Upside Down', 'Netflix', 'Kids', 'Monster'] },
            { word: 'Shrek', taboo: ['Ogre', 'Green', 'Donkey', 'Swamp', 'Princess'] },
            { word: 'Batman', taboo: ['Superhero', 'Gotham', 'Dark', 'Bruce Wayne', 'Joker'] },
            { word: 'The Simpsons', taboo: ['Homer', 'Yellow', 'Springfield', 'Cartoon', 'Bart'] },
            { word: 'Finding Nemo', taboo: ['Fish', 'Ocean', 'Clownfish', 'Dory', 'Pixar'] },
            { word: 'Inception', taboo: ['Dream', 'Sleep', 'Leonardo', 'Spinning', 'Top'] },
            { word: 'The Matrix', taboo: ['Keanu', 'Red Pill', 'Neo', 'Virtual', 'Reality'] },
            { word: 'Squid Game', taboo: ['Korean', 'Games', 'Money', 'Children', 'Netflix'] },
            { word: 'Toy Story', taboo: ['Woody', 'Buzz', 'Toys', 'Pixar', 'Andy'] },
            { word: 'Spider-Man', taboo: ['Web', 'Spider', 'Peter Parker', 'Superhero', 'Marvel'] },
            { word: 'Grey\'s Anatomy', taboo: ['Hospital', 'Doctor', 'Surgery', 'Medical', 'Seattle'] },
            { word: 'The Walking Dead', taboo: ['Zombie', 'Apocalypse', 'Rick', 'Survivor', 'AMC'] },
            { word: 'Forrest Gump', taboo: ['Tom Hanks', 'Chocolate', 'Run', 'Bench', 'Shrimp'] },
            { word: 'Black Panther', taboo: ['Wakanda', 'Marvel', 'Africa', 'Superhero', 'Vibranium'] },
            { word: 'The Crown', taboo: ['Queen', 'Royal', 'Elizabeth', 'England', 'Netflix'] },
            { word: 'Jaws', taboo: ['Shark', 'Ocean', 'Beach', 'Bite', 'Spielberg'] },
            { word: 'Minions', taboo: ['Yellow', 'Small', 'Banana', 'Evil', 'Despicable'] },
            { word: 'Oppenheimer', taboo: ['Bomb', 'Nuclear', 'Scientist', 'Manhattan', 'Nolan'] }
        ]
    },

    food: {
        id: 'food',
        name: 'Food & Drinks',
        icon: '🍕',
        cards: [
            { word: 'Pizza', taboo: ['Italian', 'Cheese', 'Pepperoni', 'Slice', 'Dough'] },
            { word: 'Sushi', taboo: ['Japanese', 'Rice', 'Fish', 'Raw', 'Roll'] },
            { word: 'Hamburger', taboo: ['Beef', 'Bun', 'Patty', 'McDonald\'s', 'Fast Food'] },
            { word: 'Ice Cream', taboo: ['Cold', 'Frozen', 'Sweet', 'Cone', 'Scoop'] },
            { word: 'Coffee', taboo: ['Caffeine', 'Morning', 'Hot', 'Starbucks', 'Bean'] },
            { word: 'Chocolate', taboo: ['Sweet', 'Cocoa', 'Candy', 'Brown', 'Dessert'] },
            { word: 'Pasta', taboo: ['Italian', 'Noodle', 'Sauce', 'Spaghetti', 'Boil'] },
            { word: 'Taco', taboo: ['Mexican', 'Shell', 'Meat', 'Tuesday', 'Tortilla'] },
            { word: 'Pancakes', taboo: ['Breakfast', 'Syrup', 'Flat', 'Stack', 'Butter'] },
            { word: 'Avocado', taboo: ['Green', 'Toast', 'Guacamole', 'Fruit', 'Millennial'] },
            { word: 'Bacon', taboo: ['Pig', 'Pork', 'Crispy', 'Breakfast', 'Strips'] },
            { word: 'Smoothie', taboo: ['Blend', 'Fruit', 'Drink', 'Healthy', 'Straw'] },
            { word: 'French Fries', taboo: ['Potato', 'Fried', 'Ketchup', 'Salt', 'McDonald\'s'] },
            { word: 'Cupcake', taboo: ['Small', 'Frosting', 'Birthday', 'Cake', 'Sweet'] },
            { word: 'Steak', taboo: ['Beef', 'Meat', 'Grill', 'Rare', 'Medium'] },
            { word: 'Popcorn', taboo: ['Movie', 'Corn', 'Butter', 'Kernel', 'Microwave'] },
            { word: 'Salad', taboo: ['Lettuce', 'Healthy', 'Vegetables', 'Dressing', 'Green'] },
            { word: 'Hot Dog', taboo: ['Sausage', 'Bun', 'Mustard', 'Baseball', 'Ketchup'] },
            { word: 'Soup', taboo: ['Liquid', 'Bowl', 'Hot', 'Spoon', 'Chicken'] },
            { word: 'Donut', taboo: ['Round', 'Hole', 'Glazed', 'Sweet', 'Police'] },
            { word: 'Ramen', taboo: ['Japanese', 'Noodle', 'Soup', 'Broth', 'College'] },
            { word: 'Wine', taboo: ['Grape', 'Alcohol', 'Red', 'White', 'Bottle'] },
            { word: 'Curry', taboo: ['Indian', 'Spicy', 'Rice', 'Yellow', 'Sauce'] },
            { word: 'Cheesecake', taboo: ['Dessert', 'Cream', 'Sweet', 'New York', 'Crust'] },
            { word: 'Burrito', taboo: ['Mexican', 'Wrap', 'Tortilla', 'Bean', 'Rice'] },
            { word: 'Lobster', taboo: ['Seafood', 'Red', 'Claw', 'Expensive', 'Shell'] },
            { word: 'Waffle', taboo: ['Breakfast', 'Square', 'Syrup', 'Belgian', 'Grid'] },
            { word: 'Croissant', taboo: ['French', 'Pastry', 'Butter', 'Flaky', 'Bread'] },
            { word: 'Bubble Tea', taboo: ['Tapioca', 'Taiwan', 'Pearls', 'Milk', 'Straw'] },
            { word: 'Nachos', taboo: ['Chips', 'Cheese', 'Mexican', 'Dip', 'Jalapeno'] }
        ]
    },

    animals: {
        id: 'animals',
        name: 'Animals',
        icon: '🐾',
        cards: [
            { word: 'Elephant', taboo: ['Trunk', 'Big', 'Gray', 'Africa', 'Tusks'] },
            { word: 'Penguin', taboo: ['Bird', 'Ice', 'Antarctica', 'Black', 'White'] },
            { word: 'Dolphin', taboo: ['Ocean', 'Smart', 'Swim', 'Mammal', 'Flipper'] },
            { word: 'Kangaroo', taboo: ['Australia', 'Jump', 'Pouch', 'Joey', 'Hop'] },
            { word: 'Giraffe', taboo: ['Tall', 'Neck', 'Spots', 'Africa', 'Zoo'] },
            { word: 'Lion', taboo: ['King', 'Jungle', 'Roar', 'Mane', 'Pride'] },
            { word: 'Butterfly', taboo: ['Wings', 'Caterpillar', 'Fly', 'Colorful', 'Insect'] },
            { word: 'Shark', taboo: ['Ocean', 'Teeth', 'Fin', 'Jaws', 'Swim'] },
            { word: 'Panda', taboo: ['China', 'Black', 'White', 'Bamboo', 'Bear'] },
            { word: 'Octopus', taboo: ['Eight', 'Tentacles', 'Ocean', 'Ink', 'Sea'] },
            { word: 'Monkey', taboo: ['Banana', 'Tree', 'Climb', 'Jungle', 'Ape'] },
            { word: 'Owl', taboo: ['Night', 'Wise', 'Hoot', 'Bird', 'Eyes'] },
            { word: 'Flamingo', taboo: ['Pink', 'Bird', 'One Leg', 'Florida', 'Stand'] },
            { word: 'Turtle', taboo: ['Shell', 'Slow', 'Reptile', 'Sea', 'Green'] },
            { word: 'Koala', taboo: ['Australia', 'Eucalyptus', 'Tree', 'Bear', 'Sleep'] },
            { word: 'Peacock', taboo: ['Feathers', 'Beautiful', 'Bird', 'Blue', 'Fan'] },
            { word: 'Polar Bear', taboo: ['Arctic', 'White', 'Ice', 'Cold', 'Coca-Cola'] },
            { word: 'Zebra', taboo: ['Stripes', 'Black', 'White', 'Horse', 'Africa'] },
            { word: 'Parrot', taboo: ['Talk', 'Bird', 'Colorful', 'Pirate', 'Feathers'] },
            { word: 'Sloth', taboo: ['Slow', 'Tree', 'Lazy', 'Hang', 'Sleep'] },
            { word: 'Cheetah', taboo: ['Fast', 'Spots', 'Run', 'Cat', 'Africa'] },
            { word: 'Whale', taboo: ['Ocean', 'Big', 'Mammal', 'Blue', 'Water'] },
            { word: 'Crocodile', taboo: ['Reptile', 'Water', 'Teeth', 'Alligator', 'Snap'] },
            { word: 'Fox', taboo: ['Red', 'Sly', 'Cunning', 'Forest', 'Dog'] },
            { word: 'Hippo', taboo: ['Water', 'Africa', 'Big', 'Mouth', 'River'] },
            { word: 'Bat', taboo: ['Fly', 'Night', 'Vampire', 'Cave', 'Wings'] },
            { word: 'Jellyfish', taboo: ['Ocean', 'Sting', 'Transparent', 'Tentacles', 'Float'] },
            { word: 'Chameleon', taboo: ['Color', 'Change', 'Lizard', 'Tongue', 'Camouflage'] },
            { word: 'Gorilla', taboo: ['Ape', 'King Kong', 'Strong', 'Jungle', 'Chest'] },
            { word: 'Hummingbird', taboo: ['Small', 'Fast', 'Wings', 'Flower', 'Hover'] }
        ]
    },

    technology: {
        id: 'technology',
        name: 'Technology',
        icon: '💻',
        cards: [
            { word: 'iPhone', taboo: ['Apple', 'Phone', 'Smart', 'iOS', 'Mobile'] },
            { word: 'Google', taboo: ['Search', 'Internet', 'Engine', 'Website', 'Browser'] },
            { word: 'WiFi', taboo: ['Internet', 'Wireless', 'Connect', 'Signal', 'Router'] },
            { word: 'Instagram', taboo: ['Photo', 'Social', 'Filter', 'Story', 'App'] },
            { word: 'Netflix', taboo: ['Stream', 'Movie', 'TV', 'Watch', 'Chill'] },
            { word: 'Amazon', taboo: ['Shop', 'Online', 'Delivery', 'Prime', 'Bezos'] },
            { word: 'YouTube', taboo: ['Video', 'Watch', 'Subscribe', 'Channel', 'Google'] },
            { word: 'Password', taboo: ['Secret', 'Login', 'Security', 'Type', 'Account'] },
            { word: 'Emoji', taboo: ['Face', 'Text', 'Symbol', 'Smiley', 'Phone'] },
            { word: 'Bluetooth', taboo: ['Wireless', 'Connect', 'Phone', 'Audio', 'Pair'] },
            { word: 'Selfie', taboo: ['Photo', 'Camera', 'Yourself', 'Phone', 'Picture'] },
            { word: 'TikTok', taboo: ['Video', 'Dance', 'Short', 'App', 'Viral'] },
            { word: 'Laptop', taboo: ['Computer', 'Portable', 'Keyboard', 'Screen', 'Work'] },
            { word: 'Spotify', taboo: ['Music', 'Stream', 'Playlist', 'Song', 'App'] },
            { word: 'Bitcoin', taboo: ['Crypto', 'Money', 'Digital', 'Currency', 'Mining'] },
            { word: 'Uber', taboo: ['Ride', 'Taxi', 'Driver', 'App', 'Car'] },
            { word: 'Zoom', taboo: ['Meeting', 'Video', 'Call', 'Virtual', 'Conference'] },
            { word: 'Alexa', taboo: ['Amazon', 'Voice', 'Assistant', 'Smart', 'Speaker'] },
            { word: 'Keyboard', taboo: ['Type', 'Keys', 'Computer', 'Letters', 'QWERTY'] },
            { word: 'Screenshot', taboo: ['Picture', 'Screen', 'Capture', 'Image', 'Save'] },
            { word: 'Hashtag', taboo: ['Twitter', 'Symbol', 'Tag', 'Pound', 'Trend'] },
            { word: 'Podcast', taboo: ['Audio', 'Listen', 'Episode', 'Talk', 'Show'] },
            { word: 'Robot', taboo: ['Machine', 'AI', 'Metal', 'Artificial', 'Human'] },
            { word: 'Drone', taboo: ['Fly', 'Camera', 'Remote', 'Aerial', 'Control'] },
            { word: 'Virtual Reality', taboo: ['VR', 'Headset', '3D', 'Immersive', 'Goggles'] },
            { word: 'USB', taboo: ['Plug', 'Connect', 'Port', 'Cable', 'Drive'] },
            { word: 'ChatGPT', taboo: ['AI', 'Chat', 'OpenAI', 'Bot', 'Artificial'] },
            { word: 'AirPods', taboo: ['Apple', 'Earbuds', 'Wireless', 'Music', 'White'] },
            { word: 'GPS', taboo: ['Navigation', 'Map', 'Location', 'Satellite', 'Direction'] },
            { word: 'Meme', taboo: ['Funny', 'Internet', 'Image', 'Viral', 'Share'] }
        ]
    },

    sports: {
        id: 'sports',
        name: 'Sports & Games',
        icon: '⚽',
        cards: [
            { word: 'Soccer', taboo: ['Football', 'Ball', 'Goal', 'Kick', 'World Cup'] },
            { word: 'Basketball', taboo: ['Hoop', 'NBA', 'Court', 'Dribble', 'Dunk'] },
            { word: 'Olympics', taboo: ['Gold', 'Medal', 'Rings', 'Games', 'Athletes'] },
            { word: 'Tennis', taboo: ['Racket', 'Ball', 'Court', 'Serve', 'Net'] },
            { word: 'Golf', taboo: ['Club', 'Ball', 'Hole', 'Swing', 'Course'] },
            { word: 'Swimming', taboo: ['Pool', 'Water', 'Stroke', 'Dive', 'Lap'] },
            { word: 'Yoga', taboo: ['Stretch', 'Pose', 'Meditation', 'Mat', 'Flexible'] },
            { word: 'Marathon', taboo: ['Run', 'Long', 'Race', '26 Miles', 'Distance'] },
            { word: 'Surfing', taboo: ['Wave', 'Board', 'Ocean', 'Beach', 'Balance'] },
            { word: 'Bowling', taboo: ['Pins', 'Ball', 'Lane', 'Strike', 'Alley'] },
            { word: 'Chess', taboo: ['Board', 'King', 'Queen', 'Strategy', 'Checkmate'] },
            { word: 'Poker', taboo: ['Cards', 'Bet', 'Chips', 'Bluff', 'Casino'] },
            { word: 'Skateboarding', taboo: ['Board', 'Wheels', 'Tricks', 'Ramp', 'Tony Hawk'] },
            { word: 'Boxing', taboo: ['Punch', 'Ring', 'Gloves', 'Fight', 'Knockout'] },
            { word: 'Volleyball', taboo: ['Net', 'Ball', 'Beach', 'Spike', 'Serve'] },
            { word: 'Skiing', taboo: ['Snow', 'Mountain', 'Slope', 'Ski', 'Winter'] },
            { word: 'Baseball', taboo: ['Bat', 'Ball', 'Home Run', 'Pitch', 'Diamond'] },
            { word: 'Gymnastics', taboo: ['Flip', 'Balance', 'Olympics', 'Beam', 'Tumble'] },
            { word: 'Hockey', taboo: ['Ice', 'Puck', 'Stick', 'Goal', 'Rink'] },
            { word: 'Monopoly', taboo: ['Board', 'Money', 'Property', 'Jail', 'Pass Go'] },
            { word: 'Cricket', taboo: ['Bat', 'Ball', 'Wicket', 'England', 'India'] },
            { word: 'Archery', taboo: ['Bow', 'Arrow', 'Target', 'Shoot', 'Aim'] },
            { word: 'Scrabble', taboo: ['Letters', 'Words', 'Board', 'Tiles', 'Points'] },
            { word: 'Karate', taboo: ['Martial Arts', 'Kick', 'Belt', 'Japan', 'Punch'] },
            { word: 'Triathlon', taboo: ['Swim', 'Bike', 'Run', 'Three', 'Ironman'] },
            { word: 'Fencing', taboo: ['Sword', 'Duel', 'Olympics', 'Touch', 'En Garde'] },
            { word: 'Darts', taboo: ['Throw', 'Board', 'Bullseye', 'Points', 'Pub'] },
            { word: 'Rock Climbing', taboo: ['Wall', 'Climb', 'Rope', 'Mountain', 'Hold'] },
            { word: 'Formula 1', taboo: ['Race', 'Car', 'Fast', 'Driver', 'Track'] },
            { word: 'Crossword', taboo: ['Puzzle', 'Words', 'Clues', 'Across', 'Down'] }
        ]
    },

    travel: {
        id: 'travel',
        name: 'Travel & Places',
        icon: '🌍',
        cards: [
            { word: 'Eiffel Tower', taboo: ['Paris', 'France', 'Metal', 'Tall', 'Landmark'] },
            { word: 'Grand Canyon', taboo: ['Arizona', 'Big', 'Red', 'Colorado', 'National Park'] },
            { word: 'Pyramids', taboo: ['Egypt', 'Ancient', 'Triangle', 'Pharaoh', 'Giza'] },
            { word: 'Great Wall', taboo: ['China', 'Long', 'Stone', 'Ancient', 'Wall'] },
            { word: 'Statue of Liberty', taboo: ['New York', 'America', 'Green', 'Torch', 'Freedom'] },
            { word: 'Taj Mahal', taboo: ['India', 'White', 'Marble', 'Tomb', 'Love'] },
            { word: 'Big Ben', taboo: ['London', 'Clock', 'Tower', 'England', 'Time'] },
            { word: 'Colosseum', taboo: ['Rome', 'Italy', 'Ancient', 'Gladiator', 'Arena'] },
            { word: 'Safari', taboo: ['Africa', 'Animals', 'Wild', 'Jeep', 'Lion'] },
            { word: 'Cruise', taboo: ['Ship', 'Ocean', 'Vacation', 'Boat', 'Caribbean'] },
            { word: 'Passport', taboo: ['Travel', 'Document', 'Country', 'Photo', 'Border'] },
            { word: 'Beach', taboo: ['Sand', 'Ocean', 'Sun', 'Wave', 'Swim'] },
            { word: 'Airport', taboo: ['Plane', 'Fly', 'Terminal', 'Gate', 'Travel'] },
            { word: 'Hotel', taboo: ['Room', 'Stay', 'Sleep', 'Vacation', 'Bed'] },
            { word: 'Backpacking', taboo: ['Travel', 'Bag', 'Hike', 'Hostel', 'Europe'] },
            { word: 'Niagara Falls', taboo: ['Water', 'Canada', 'USA', 'Waterfall', 'Border'] },
            { word: 'Hollywood', taboo: ['Movies', 'Los Angeles', 'Stars', 'California', 'Sign'] },
            { word: 'Venice', taboo: ['Italy', 'Canals', 'Gondola', 'Water', 'Boat'] },
            { word: 'Mount Everest', taboo: ['Mountain', 'Tall', 'Climb', 'Nepal', 'Peak'] },
            { word: 'Tokyo', taboo: ['Japan', 'City', 'Sushi', 'Capital', 'Anime'] },
            { word: 'Machu Picchu', taboo: ['Peru', 'Inca', 'Mountain', 'Ancient', 'Ruins'] },
            { word: 'Sydney Opera House', taboo: ['Australia', 'Music', 'Building', 'White', 'Harbor'] },
            { word: 'Amazon Rainforest', taboo: ['Brazil', 'Jungle', 'Trees', 'River', 'South America'] },
            { word: 'Las Vegas', taboo: ['Casino', 'Gambling', 'Nevada', 'Strip', 'Sin City'] },
            { word: 'Santorini', taboo: ['Greece', 'Island', 'Blue', 'White', 'Mediterranean'] },
            { word: 'Stonehenge', taboo: ['England', 'Rocks', 'Ancient', 'Mystery', 'Circle'] },
            { word: 'Dubai', taboo: ['UAE', 'Rich', 'Tall Buildings', 'Desert', 'Luxury'] },
            { word: 'Northern Lights', taboo: ['Aurora', 'Sky', 'Green', 'Arctic', 'Norway'] },
            { word: 'Disneyland', taboo: ['Mickey', 'Theme Park', 'Disney', 'Castle', 'Rides'] },
            { word: 'Great Barrier Reef', taboo: ['Australia', 'Coral', 'Ocean', 'Dive', 'Fish'] }
        ]
    }
};

// Export for use in main game
if (typeof module !== 'undefined' && module.exports) {
    module.exports = DECKS;
}
