/**
 * Nono Game - Card Decks
 * Each deck contains cards with a word and 5 taboo words that cannot be used
 */

const DECKS = {
    movies: {
        id: 'movies',
        name: 'Movies & TV',
        icon: '🎬',
        cards: [
            { word: 'Harry Potter', taboo: ['Wizard', 'Magic', 'Hogwarts', 'Wand', 'Voldemort'] },
            { word: 'Titanic', taboo: ['Ship', 'Sink', 'Iceberg', 'Rose', 'Jack'] },
            { word: 'Star Wars', taboo: ['Space', 'Jedi', 'Force', 'Lightsaber', 'Darth Vader'] },
            { word: 'The Lion King', taboo: ['Simba', 'Africa', 'Mufasa', 'Jungle', 'Disney'] },
            { word: 'Friends', taboo: ['Sitcom', 'Rachel', 'Central Perk', 'New York', 'Apartment'] },
            { word: 'Avatar', taboo: ['Blue', 'Alien', 'Pandora', 'James Cameron', '3D'] },
            { word: 'Breaking Bad', taboo: ['Meth', 'Chemistry', 'Walter', 'Teacher', 'Drug'] },
            { word: 'The Office', taboo: ['Michael Scott', 'Dunder', 'Paper', 'Scranton', 'Boss'] },
            { word: 'Frozen', taboo: ['Elsa', 'Ice', 'Snow', 'Let It Go', 'Anna'] },
            { word: 'Game of Thrones', taboo: ['Dragon', 'Winter', 'Throne', 'King', 'Westeros'] },
            { word: 'Jurassic Park', taboo: ['Dinosaur', 'T-Rex', 'Island', 'Spielberg', 'DNA'] },
            { word: 'The Godfather', taboo: ['Mafia', 'Italian', 'Family', 'Corleone', 'Offer'] },
            { word: 'Stranger Things', taboo: ['Eleven', 'Upside Down', 'Netflix', 'Kids', 'Monster'] },
            { word: 'Shrek', taboo: ['Ogre', 'Green', 'Donkey', 'Swamp', 'Princess'] },
            { word: 'Batman', taboo: ['Superhero', 'Gotham', 'Dark', 'Bruce Wayne', 'Joker'] },
            { word: 'The Simpsons', taboo: ['Homer', 'Yellow', 'Springfield', 'Cartoon', 'Bart'] },
            { word: 'Finding Nemo', taboo: ['Fish', 'Ocean', 'Clownfish', 'Dory', 'Pixar'] },
            { word: 'Inception', taboo: ['Dream', 'Sleep', 'Leonardo', 'Spinning', 'Top'] },
            { word: 'The Matrix', taboo: ['Keanu', 'Red Pill', 'Neo', 'Virtual', 'Reality'] },
            { word: 'Squid Game', taboo: ['Korean', 'Games', 'Money', 'Children', 'Netflix'] },
            { word: 'Toy Story', taboo: ['Woody', 'Buzz', 'Toys', 'Pixar', 'Andy'] },
            { word: 'Spider-Man', taboo: ['Web', 'Spider', 'Peter Parker', 'Superhero', 'Marvel'] },
            { word: 'Grey\'s Anatomy', taboo: ['Hospital', 'Doctor', 'Surgery', 'Medical', 'Seattle'] },
            { word: 'The Walking Dead', taboo: ['Zombie', 'Apocalypse', 'Rick', 'Survivor', 'AMC'] },
            { word: 'Forrest Gump', taboo: ['Tom Hanks', 'Chocolate', 'Run', 'Bench', 'Shrimp'] },
            { word: 'Black Panther', taboo: ['Wakanda', 'Marvel', 'Africa', 'Superhero', 'Vibranium'] },
            { word: 'The Crown', taboo: ['Queen', 'Royal', 'Elizabeth', 'England', 'Netflix'] },
            { word: 'Jaws', taboo: ['Shark', 'Ocean', 'Beach', 'Bite', 'Spielberg'] },
            { word: 'Minions', taboo: ['Yellow', 'Small', 'Banana', 'Evil', 'Despicable'] },
            { word: 'Oppenheimer', taboo: ['Bomb', 'Nuclear', 'Scientist', 'Manhattan', 'Nolan'] }
        ]
    },

    food: {
        id: 'food',
        name: 'Food & Drinks',
        icon: '🍕',
        cards: [
            { word: 'Pizza', taboo: ['Italian', 'Cheese', 'Pepperoni', 'Slice', 'Dough'] },
            { word: 'Sushi', taboo: ['Japanese', 'Rice', 'Fish', 'Raw', 'Roll'] },
            { word: 'Hamburger', taboo: ['Beef', 'Bun', 'Patty', 'McDonald\'s', 'Fast Food'] },
            { word: 'Ice Cream', taboo: ['Cold', 'Frozen', 'Sweet', 'Cone', 'Scoop'] },
            { word: 'Coffee', taboo: ['Caffeine', 'Morning', 'Hot', 'Starbucks', 'Bean'] },
            { word: 'Chocolate', taboo: ['Sweet', 'Cocoa', 'Candy', 'Brown', 'Dessert'] },
            { word: 'Pasta', taboo: ['Italian', 'Noodle', 'Sauce', 'Spaghetti', 'Boil'] },
            { word: 'Taco', taboo: ['Mexican', 'Shell', 'Meat', 'Tuesday', 'Tortilla'] },
            { word: 'Pancakes', taboo: ['Breakfast', 'Syrup', 'Flat', 'Stack', 'Butter'] },
            { word: 'Avocado', taboo: ['Green', 'Toast', 'Guacamole', 'Fruit', 'Millennial'] },
            { word: 'Bacon', taboo: ['Pig', 'Pork', 'Crispy', 'Breakfast', 'Strips'] },
            { word: 'Smoothie', taboo: ['Blend', 'Fruit', 'Drink', 'Healthy', 'Straw'] },
            { word: 'French Fries', taboo: ['Potato', 'Fried', 'Ketchup', 'Salt', 'McDonald\'s'] },
            { word: 'Cupcake', taboo: ['Small', 'Frosting', 'Birthday', 'Cake', 'Sweet'] },
            { word: 'Steak', taboo: ['Beef', 'Meat', 'Grill', 'Rare', 'Medium'] },
            { word: 'Popcorn', taboo: ['Movie', 'Corn', 'Butter', 'Kernel', 'Microwave'] },
            { word: 'Salad', taboo: ['Lettuce', 'Healthy', 'Vegetables', 'Dressing', 'Green'] },
            { word: 'Hot Dog', taboo: ['Sausage', 'Bun', 'Mustard', 'Baseball', 'Ketchup'] },
            { word: 'Soup', taboo: ['Liquid', 'Bowl', 'Hot', 'Spoon', 'Chicken'] },
            { word: 'Donut', taboo: ['Round', 'Hole', 'Glazed', 'Sweet', 'Police'] },
            { word: 'Ramen', taboo: ['Japanese', 'Noodle', 'Soup', 'Broth', 'College'] },
            { word: 'Wine', taboo: ['Grape', 'Alcohol', 'Red', 'White', 'Bottle'] },
            { word: 'Curry', taboo: ['Indian', 'Spicy', 'Rice', 'Yellow', 'Sauce'] },
            { word: 'Cheesecake', taboo: ['Dessert', 'Cream', 'Sweet', 'New York', 'Crust'] },
            { word: 'Burrito', taboo: ['Mexican', 'Wrap', 'Tortilla', 'Bean', 'Rice'] },
            { word: 'Lobster', taboo: ['Seafood', 'Red', 'Claw', 'Expensive', 'Shell'] },
            { word: 'Waffle', taboo: ['Breakfast', 'Square', 'Syrup', 'Belgian', 'Grid'] },
            { word: 'Croissant', taboo: ['French', 'Pastry', 'Butter', 'Flaky', 'Bread'] },
            { word: 'Bubble Tea', taboo: ['Tapioca', 'Taiwan', 'Pearls', 'Milk', 'Straw'] },
            { word: 'Nachos', taboo: ['Chips', 'Cheese', 'Mexican', 'Dip', 'Jalapeno'] }
        ]
    },

    animals: {
        id: 'animals',
        name: 'Animals',
        icon: '🐾',
        cards: [
            { word: 'Elephant', taboo: ['Trunk', 'Big', 'Gray', 'Africa', 'Tusks'] },
            { word: 'Penguin', taboo: ['Bird', 'Ice', 'Antarctica', 'Black', 'White'] },
            { word: 'Dolphin', taboo: ['Ocean', 'Smart', 'Swim', 'Mammal', 'Flipper'] },
            { word: 'Kangaroo', taboo: ['Australia', 'Jump', 'Pouch', 'Joey', 'Hop'] },
            { word: 'Giraffe', taboo: ['Tall', 'Neck', 'Spots', 'Africa', 'Zoo'] },
            { word: 'Lion', taboo: ['King', 'Jungle', 'Roar', 'Mane', 'Pride'] },
            { word: 'Butterfly', taboo: ['Wings', 'Caterpillar', 'Fly', 'Colorful', 'Insect'] },
            { word: 'Shark', taboo: ['Ocean', 'Teeth', 'Fin', 'Jaws', 'Swim'] },
            { word: 'Panda', taboo: ['China', 'Black', 'White', 'Bamboo', 'Bear'] },
            { word: 'Octopus', taboo: ['Eight', 'Tentacles', 'Ocean', 'Ink', 'Sea'] },
            { word: 'Monkey', taboo: ['Banana', 'Tree', 'Climb', 'Jungle', 'Ape'] },
            { word: 'Owl', taboo: ['Night', 'Wise', 'Hoot', 'Bird', 'Eyes'] },
            { word: 'Flamingo', taboo: ['Pink', 'Bird', 'One Leg', 'Florida', 'Stand'] },
            { word: 'Turtle', taboo: ['Shell', 'Slow', 'Reptile', 'Sea', 'Green'] },
            { word: 'Koala', taboo: ['Australia', 'Eucalyptus', 'Tree', 'Bear', 'Sleep'] },
            { word: 'Peacock', taboo: ['Feathers', 'Beautiful', 'Bird', 'Blue', 'Fan'] },
            { word: 'Polar Bear', taboo: ['Arctic', 'White', 'Ice', 'Cold', 'Coca-Cola'] },
            { word: 'Zebra', taboo: ['Stripes', 'Black', 'White', 'Horse', 'Africa'] },
            { word: 'Parrot', taboo: ['Talk', 'Bird', 'Colorful', 'Pirate', 'Feathers'] },
            { word: 'Sloth', taboo: ['Slow', 'Tree', 'Lazy', 'Hang', 'Sleep'] },
            { word: 'Cheetah', taboo: ['Fast', 'Spots', 'Run', 'Cat', 'Africa'] },
            { word: 'Whale', taboo: ['Ocean', 'Big', 'Mammal', 'Blue', 'Water'] },
            { word: 'Crocodile', taboo: ['Reptile', 'Water', 'Teeth', 'Alligator', 'Snap'] },
            { word: 'Fox', taboo: ['Red', 'Sly', 'Cunning', 'Forest', 'Dog'] },
            { word: 'Hippo', taboo: ['Water', 'Africa', 'Big', 'Mouth', 'River'] },
            { word: 'Bat', taboo: ['Fly', 'Night', 'Vampire', 'Cave', 'Wings'] },
            { word: 'Jellyfish', taboo: ['Ocean', 'Sting', 'Transparent', 'Tentacles', 'Float'] },
            { word: 'Chameleon', taboo: ['Color', 'Change', 'Lizard', 'Tongue', 'Camouflage'] },
            { word: 'Gorilla', taboo: ['Ape', 'King Kong', 'Strong', 'Jungle', 'Chest'] },
            { word: 'Hummingbird', taboo: ['Small', 'Fast', 'Wings', 'Flower', 'Hover'] }
        ]
    },

    technology: {
        id: 'technology',
        name: 'Technology',
        icon: '💻',
        cards: [
            { word: 'iPhone', taboo: ['Apple', 'Phone', 'Smart', 'iOS', 'Mobile'] },
            { word: 'Google', taboo: ['Search', 'Internet', 'Engine', 'Website', 'Browser'] },
            { word: 'WiFi', taboo: ['Internet', 'Wireless', 'Connect', 'Signal', 'Router'] },
            { word: 'Instagram', taboo: ['Photo', 'Social', 'Filter', 'Story', 'App'] },
            { word: 'Netflix', taboo: ['Stream', 'Movie', 'TV', 'Watch', 'Chill'] },
            { word: 'Amazon', taboo: ['Shop', 'Online', 'Delivery', 'Prime', 'Bezos'] },
            { word: 'YouTube', taboo: ['Video', 'Watch', 'Subscribe', 'Channel', 'Google'] },
            { word: 'Password', taboo: ['Secret', 'Login', 'Security', 'Type', 'Account'] },
            { word: 'Emoji', taboo: ['Face', 'Text', 'Symbol', 'Smiley', 'Phone'] },
            { word: 'Bluetooth', taboo: ['Wireless', 'Connect', 'Phone', 'Audio', 'Pair'] },
            { word: 'Selfie', taboo: ['Photo', 'Camera', 'Yourself', 'Phone', 'Picture'] },
            { word: 'TikTok', taboo: ['Video', 'Dance', 'Short', 'App', 'Viral'] },
            { word: 'Laptop', taboo: ['Computer', 'Portable', 'Keyboard', 'Screen', 'Work'] },
            { word: 'Spotify', taboo: ['Music', 'Stream', 'Playlist', 'Song', 'App'] },
            { word: 'Bitcoin', taboo: ['Crypto', 'Money', 'Digital', 'Currency', 'Mining'] },
            { word: 'Uber', taboo: ['Ride', 'Taxi', 'Driver', 'App', 'Car'] },
            { word: 'Zoom', taboo: ['Meeting', 'Video', 'Call', 'Virtual', 'Conference'] },
            { word: 'Alexa', taboo: ['Amazon', 'Voice', 'Assistant', 'Smart', 'Speaker'] },
            { word: 'Keyboard', taboo: ['Type', 'Keys', 'Computer', 'Letters', 'QWERTY'] },
            { word: 'Screenshot', taboo: ['Picture', 'Screen', 'Capture', 'Image', 'Save'] },
            { word: 'Hashtag', taboo: ['Twitter', 'Symbol', 'Tag', 'Pound', 'Trend'] },
            { word: 'Podcast', taboo: ['Audio', 'Listen', 'Episode', 'Talk', 'Show'] },
            { word: 'Robot', taboo: ['Machine', 'AI', 'Metal', 'Artificial', 'Human'] },
            { word: 'Drone', taboo: ['Fly', 'Camera', 'Remote', 'Aerial', 'Control'] },
            { word: 'Virtual Reality', taboo: ['VR', 'Headset', '3D', 'Immersive', 'Goggles'] },
            { word: 'USB', taboo: ['Plug', 'Connect', 'Port', 'Cable', 'Drive'] },
            { word: 'ChatGPT', taboo: ['AI', 'Chat', 'OpenAI', 'Bot', 'Artificial'] },
            { word: 'AirPods', taboo: ['Apple', 'Earbuds', 'Wireless', 'Music', 'White'] },
            { word: 'GPS', taboo: ['Navigation', 'Map', 'Location', 'Satellite', 'Direction'] },
            { word: 'Meme', taboo: ['Funny', 'Internet', 'Image', 'Viral', 'Share'] }
        ]
    },

    sports: {
        id: 'sports',
        name: 'Sports & Games',
        icon: '⚽',
        cards: [
            { word: 'Soccer', taboo: ['Football', 'Ball', 'Goal', 'Kick', 'World Cup'] },
            { word: 'Basketball', taboo: ['Hoop', 'NBA', 'Court', 'Dribble', 'Dunk'] },
            { word: 'Olympics', taboo: ['Gold', 'Medal', 'Rings', 'Games', 'Athletes'] },
            { word: 'Tennis', taboo: ['Racket', 'Ball', 'Court', 'Serve', 'Net'] },
            { word: 'Golf', taboo: ['Club', 'Ball', 'Hole', 'Swing', 'Course'] },
            { word: 'Swimming', taboo: ['Pool', 'Water', 'Stroke', 'Dive', 'Lap'] },
            { word: 'Yoga', taboo: ['Stretch', 'Pose', 'Meditation', 'Mat', 'Flexible'] },
            { word: 'Marathon', taboo: ['Run', 'Long', 'Race', '26 Miles', 'Distance'] },
            { word: 'Surfing', taboo: ['Wave', 'Board', 'Ocean', 'Beach', 'Balance'] },
            { word: 'Bowling', taboo: ['Pins', 'Ball', 'Lane', 'Strike', 'Alley'] },
            { word: 'Chess', taboo: ['Board', 'King', 'Queen', 'Strategy', 'Checkmate'] },
            { word: 'Poker', taboo: ['Cards', 'Bet', 'Chips', 'Bluff', 'Casino'] },
            { word: 'Skateboarding', taboo: ['Board', 'Wheels', 'Tricks', 'Ramp', 'Tony Hawk'] },
            { word: 'Boxing', taboo: ['Punch', 'Ring', 'Gloves', 'Fight', 'Knockout'] },
            { word: 'Volleyball', taboo: ['Net', 'Ball', 'Beach', 'Spike', 'Serve'] },
            { word: 'Skiing', taboo: ['Snow', 'Mountain', 'Slope', 'Ski', 'Winter'] },
            { word: 'Baseball', taboo: ['Bat', 'Ball', 'Home Run', 'Pitch', 'Diamond'] },
            { word: 'Gymnastics', taboo: ['Flip', 'Balance', 'Olympics', 'Beam', 'Tumble'] },
            { word: 'Hockey', taboo: ['Ice', 'Puck', 'Stick', 'Goal', 'Rink'] },
            { word: 'Monopoly', taboo: ['Board', 'Money', 'Property', 'Jail', 'Pass Go'] },
            { word: 'Cricket', taboo: ['Bat', 'Ball', 'Wicket', 'England', 'India'] },
            { word: 'Archery', taboo: ['Bow', 'Arrow', 'Target', 'Shoot', 'Aim'] },
            { word: 'Scrabble', taboo: ['Letters', 'Words', 'Board', 'Tiles', 'Points'] },
            { word: 'Karate', taboo: ['Martial Arts', 'Kick', 'Belt', 'Japan', 'Punch'] },
            { word: 'Triathlon', taboo: ['Swim', 'Bike', 'Run', 'Three', 'Ironman'] },
            { word: 'Fencing', taboo: ['Sword', 'Duel', 'Olympics', 'Touch', 'En Garde'] },
            { word: 'Darts', taboo: ['Throw', 'Board', 'Bullseye', 'Points', 'Pub'] },
            { word: 'Rock Climbing', taboo: ['Wall', 'Climb', 'Rope', 'Mountain', 'Hold'] },
            { word: 'Formula 1', taboo: ['Race', 'Car', 'Fast', 'Driver', 'Track'] },
            { word: 'Crossword', taboo: ['Puzzle', 'Words', 'Clues', 'Across', 'Down'] }
        ]
    },

    travel: {
        id: 'travel',
        name: 'Travel & Places',
        icon: '🌍',
        cards: [
            { word: 'Eiffel Tower', taboo: ['Paris', 'France', 'Metal', 'Tall', 'Landmark'] },
            { word: 'Grand Canyon', taboo: ['Arizona', 'Big', 'Red', 'Colorado', 'National Park'] },
            { word: 'Pyramids', taboo: ['Egypt', 'Ancient', 'Triangle', 'Pharaoh', 'Giza'] },
            { word: 'Great Wall', taboo: ['China', 'Long', 'Stone', 'Ancient', 'Wall'] },
            { word: 'Statue of Liberty', taboo: ['New York', 'America', 'Green', 'Torch', 'Freedom'] },
            { word: 'Taj Mahal', taboo: ['India', 'White', 'Marble', 'Tomb', 'Love'] },
            { word: 'Big Ben', taboo: ['London', 'Clock', 'Tower', 'England', 'Time'] },
            { word: 'Colosseum', taboo: ['Rome', 'Italy', 'Ancient', 'Gladiator', 'Arena'] },
            { word: 'Safari', taboo: ['Africa', 'Animals', 'Wild', 'Jeep', 'Lion'] },
            { word: 'Cruise', taboo: ['Ship', 'Ocean', 'Vacation', 'Boat', 'Caribbean'] },
            { word: 'Passport', taboo: ['Travel', 'Document', 'Country', 'Photo', 'Border'] },
            { word: 'Beach', taboo: ['Sand', 'Ocean', 'Sun', 'Wave', 'Swim'] },
            { word: 'Airport', taboo: ['Plane', 'Fly', 'Terminal', 'Gate', 'Travel'] },
            { word: 'Hotel', taboo: ['Room', 'Stay', 'Sleep', 'Vacation', 'Bed'] },
            { word: 'Backpacking', taboo: ['Travel', 'Bag', 'Hike', 'Hostel', 'Europe'] },
            { word: 'Niagara Falls', taboo: ['Water', 'Canada', 'USA', 'Waterfall', 'Border'] },
            { word: 'Hollywood', taboo: ['Movies', 'Los Angeles', 'Stars', 'California', 'Sign'] },
            { word: 'Venice', taboo: ['Italy', 'Canals', 'Gondola', 'Water', 'Boat'] },
            { word: 'Mount Everest', taboo: ['Mountain', 'Tall', 'Climb', 'Nepal', 'Peak'] },
            { word: 'Tokyo', taboo: ['Japan', 'City', 'Sushi', 'Capital', 'Anime'] },
            { word: 'Machu Picchu', taboo: ['Peru', 'Inca', 'Mountain', 'Ancient', 'Ruins'] },
            { word: 'Sydney Opera House', taboo: ['Australia', 'Music', 'Building', 'White', 'Harbor'] },
            { word: 'Amazon Rainforest', taboo: ['Brazil', 'Jungle', 'Trees', 'River', 'South America'] },
            { word: 'Las Vegas', taboo: ['Casino', 'Gambling', 'Nevada', 'Strip', 'Sin City'] },
            { word: 'Santorini', taboo: ['Greece', 'Island', 'Blue', 'White', 'Mediterranean'] },
            { word: 'Stonehenge', taboo: ['England', 'Rocks', 'Ancient', 'Mystery', 'Circle'] },
            { word: 'Dubai', taboo: ['UAE', 'Rich', 'Tall Buildings', 'Desert', 'Luxury'] },
            { word: 'Northern Lights', taboo: ['Aurora', 'Sky', 'Green', 'Arctic', 'Norway'] },
            { word: 'Disneyland', taboo: ['Mickey', 'Theme Park', 'Disney', 'Castle', 'Rides'] },
            { word: 'Great Barrier Reef', taboo: ['Australia', 'Coral', 'Ocean', 'Dive', 'Fish'] }
        ]
    },

    slang: {
        id: 'slang',
        name: 'Teen Slang',
        icon: '🗣️',
        cards: [
            // Modern 2020s slang
            { word: 'Slay', taboo: ['Kill', 'Amazing', 'Good', 'Awesome', 'Queen'] },
            { word: 'No Cap', taboo: ['Truth', 'Honest', 'Lie', 'Real', 'Serious'] },
            { word: 'Bussin', taboo: ['Good', 'Delicious', 'Amazing', 'Food', 'Great'] },
            { word: 'Rizz', taboo: ['Charm', 'Flirt', 'Game', 'Charisma', 'Attractive'] },
            { word: 'Bet', taboo: ['Okay', 'Yes', 'Sure', 'Agree', 'Deal'] },
            { word: 'Sus', taboo: ['Suspicious', 'Weird', 'Strange', 'Shady', 'Among Us'] },
            { word: 'Mid', taboo: ['Average', 'Mediocre', 'Okay', 'Nothing Special', 'Meh'] },
            { word: 'Lowkey', taboo: ['Secretly', 'Quietly', 'Kind Of', 'Subtle', 'Little'] },
            { word: 'Highkey', taboo: ['Obviously', 'Very', 'Really', 'Openly', 'Definitely'] },
            { word: 'Stan', taboo: ['Fan', 'Love', 'Support', 'Obsessed', 'Follow'] },
            { word: 'Simp', taboo: ['Desperate', 'Obsessed', 'Crush', 'Worship', 'Attention'] },
            { word: 'Ghosting', taboo: ['Ignore', 'Disappear', 'Stop Talking', 'Text', 'Leave'] },
            { word: 'Vibe Check', taboo: ['Energy', 'Mood', 'Feel', 'Atmosphere', 'Test'] },
            { word: 'Catch Feelings', taboo: ['Fall', 'Love', 'Like', 'Romantic', 'Emotions'] },
            { word: 'Slaps', taboo: ['Good', 'Music', 'Song', 'Great', 'Hits'] },
            { word: 'Hits Different', taboo: ['Special', 'Unique', 'Feel', 'Better', 'Way'] },
            { word: 'Living Rent Free', taboo: ['Mind', 'Think', 'Head', 'Obsessed', 'Stuck'] },
            { word: 'Main Character', taboo: ['Protagonist', 'Star', 'Center', 'Attention', 'Movie'] },
            { word: 'NPC', taboo: ['Background', 'Boring', 'Game', 'Character', 'Basic'] },
            { word: 'Era', taboo: ['Phase', 'Time', 'Period', 'Taylor Swift', 'Chapter'] },
            { word: 'Ate', taboo: ['Killed It', 'Slayed', 'Amazing', 'Did Well', 'Performance'] },
            { word: 'Mother', taboo: ['Queen', 'Icon', 'Legend', 'Serve', 'Slay'] },
            { word: 'Understood the Assignment', taboo: ['Did Well', 'Nailed It', 'Perfect', 'Task', 'Job'] },
            { word: 'Glow Up', taboo: ['Transformation', 'Better', 'Improve', 'Change', 'Hot'] },
            { word: 'Periodt', taboo: ['Period', 'End', 'Final', 'That\'s It', 'Done'] },
            // Rating slang
            { word: 'Six Out of Seven', taboo: ['Rating', 'Number', 'Scale', 'Score', 'Almost Perfect'] },
            { word: 'Ten Out of Ten', taboo: ['Perfect', 'Score', 'Rating', 'Best', 'Hundred'] },
            // Classic/older slang still used
            { word: 'GOAT', taboo: ['Greatest', 'Best', 'All Time', 'Legend', 'Animal'] },
            { word: 'Salty', taboo: ['Bitter', 'Angry', 'Upset', 'Mad', 'Jealous'] },
            { word: 'Tea', taboo: ['Gossip', 'Drama', 'News', 'Spill', 'Secret'] },
            { word: 'Shade', taboo: ['Insult', 'Diss', 'Disrespect', 'Mean', 'Subtle'] },
            { word: 'Flex', taboo: ['Show Off', 'Brag', 'Flaunt', 'Muscle', 'Display'] },
            { word: 'Clout', taboo: ['Fame', 'Influence', 'Popular', 'Status', 'Power'] },
            { word: 'Fire', taboo: ['Hot', 'Good', 'Cool', 'Awesome', 'Flame'] },
            { word: 'Lit', taboo: ['Fun', 'Exciting', 'Party', 'Awesome', 'Cool'] },
            { word: 'Snatched', taboo: ['Perfect', 'On Point', 'Tight', 'Good', 'Flawless'] }
        ]
    },

    geography: {
        id: 'geography',
        name: 'Geography',
        icon: '🗺️',
        cards: [
            { word: 'Equator', taboo: ['Line', 'Middle', 'Earth', 'Hot', 'Zero Degrees'] },
            { word: 'Volcano', taboo: ['Lava', 'Erupt', 'Mountain', 'Hot', 'Magma'] },
            { word: 'Desert', taboo: ['Sand', 'Hot', 'Dry', 'Sahara', 'Cactus'] },
            { word: 'Continent', taboo: ['Land', 'Mass', 'Seven', 'Earth', 'Africa'] },
            { word: 'Ocean', taboo: ['Water', 'Sea', 'Pacific', 'Atlantic', 'Salt'] },
            { word: 'Island', taboo: ['Water', 'Surrounded', 'Land', 'Beach', 'Hawaii'] },
            { word: 'Peninsula', taboo: ['Land', 'Water', 'Three Sides', 'Florida', 'Italy'] },
            { word: 'Glacier', taboo: ['Ice', 'Cold', 'Frozen', 'Melt', 'Mountain'] },
            { word: 'Rainforest', taboo: ['Trees', 'Jungle', 'Amazon', 'Tropical', 'Rain'] },
            { word: 'Tundra', taboo: ['Cold', 'Arctic', 'Frozen', 'Permafrost', 'Treeless'] },
            { word: 'Delta', taboo: ['River', 'Mouth', 'Triangle', 'Sediment', 'Water'] },
            { word: 'Archipelago', taboo: ['Islands', 'Chain', 'Group', 'Water', 'Indonesia'] },
            { word: 'Fjord', taboo: ['Norway', 'Water', 'Cliff', 'Inlet', 'Glacier'] },
            { word: 'Plateau', taboo: ['Flat', 'High', 'Table', 'Land', 'Elevated'] },
            { word: 'Strait', taboo: ['Water', 'Narrow', 'Channel', 'Connect', 'Ocean'] },
            { word: 'Longitude', taboo: ['Lines', 'East', 'West', 'Meridian', 'Map'] },
            { word: 'Latitude', taboo: ['Lines', 'North', 'South', 'Parallel', 'Equator'] },
            { word: 'Hemisphere', taboo: ['Half', 'Earth', 'North', 'South', 'Sphere'] },
            { word: 'Tropics', taboo: ['Hot', 'Equator', 'Cancer', 'Capricorn', 'Warm'] },
            { word: 'Mediterranean', taboo: ['Sea', 'Europe', 'Africa', 'Climate', 'Italy'] },
            { word: 'Antarctica', taboo: ['South Pole', 'Ice', 'Cold', 'Penguins', 'Continent'] },
            { word: 'Sahara', taboo: ['Desert', 'Africa', 'Sand', 'Hot', 'Largest'] },
            { word: 'Amazon River', taboo: ['Brazil', 'Longest', 'South America', 'Rainforest', 'Water'] },
            { word: 'Himalayas', taboo: ['Mountains', 'Everest', 'Asia', 'Nepal', 'Tall'] },
            { word: 'Nile River', taboo: ['Egypt', 'Africa', 'Longest', 'Water', 'Pyramid'] },
            { word: 'Great Lakes', taboo: ['Five', 'Michigan', 'Superior', 'Water', 'North America'] },
            { word: 'Caribbean', taboo: ['Islands', 'Sea', 'Jamaica', 'Tropical', 'Pirates'] },
            { word: 'Alps', taboo: ['Mountains', 'Europe', 'Switzerland', 'Ski', 'Snow'] },
            { word: 'Coral Reef', taboo: ['Ocean', 'Fish', 'Underwater', 'Barrier', 'Australia'] },
            { word: 'Waterfall', taboo: ['Water', 'Fall', 'Niagara', 'Cliff', 'River'] }
        ]
    },

    skincare: {
        id: 'skincare',
        name: 'Skincare',
        icon: '✨',
        cards: [
            { word: 'Moisturizer', taboo: ['Hydrate', 'Cream', 'Dry', 'Lotion', 'Skin'] },
            { word: 'Sunscreen', taboo: ['SPF', 'Sun', 'Protection', 'UV', 'Burn'] },
            { word: 'Retinol', taboo: ['Vitamin A', 'Anti-Aging', 'Wrinkles', 'Night', 'Serum'] },
            { word: 'Cleanser', taboo: ['Wash', 'Face', 'Clean', 'Soap', 'Dirt'] },
            { word: 'Toner', taboo: ['pH', 'Balance', 'Pores', 'Water', 'After Cleanser'] },
            { word: 'Serum', taboo: ['Concentrated', 'Dropper', 'Active', 'Ingredients', 'Light'] },
            { word: 'Exfoliate', taboo: ['Scrub', 'Dead Skin', 'Remove', 'Smooth', 'Peel'] },
            { word: 'Hyaluronic Acid', taboo: ['Hydration', 'Moisture', 'Plump', 'Water', 'Serum'] },
            { word: 'Vitamin C', taboo: ['Brightening', 'Orange', 'Antioxidant', 'Glow', 'Dark Spots'] },
            { word: 'Niacinamide', taboo: ['Vitamin B3', 'Pores', 'Oil', 'Redness', 'Barrier'] },
            { word: 'Sheet Mask', taboo: ['Korean', 'Face', 'Paper', 'Serum', 'Relax'] },
            { word: 'Eye Cream', taboo: ['Dark Circles', 'Wrinkles', 'Puffy', 'Under', 'Bags'] },
            { word: 'Acne', taboo: ['Pimple', 'Breakout', 'Zit', 'Skin', 'Blemish'] },
            { word: 'Blackheads', taboo: ['Pores', 'Nose', 'Clogged', 'Sebum', 'Dark'] },
            { word: 'Pores', taboo: ['Holes', 'Skin', 'Large', 'Minimize', 'Clogged'] },
            { word: 'Oily Skin', taboo: ['Shiny', 'Sebum', 'Greasy', 'T-Zone', 'Matte'] },
            { word: 'Dry Skin', taboo: ['Flaky', 'Tight', 'Moisturize', 'Hydrate', 'Rough'] },
            { word: 'Sensitive Skin', taboo: ['Red', 'Irritation', 'Gentle', 'React', 'Fragrance-Free'] },
            { word: 'Double Cleanse', taboo: ['Oil', 'Water', 'Two', 'Korean', 'Makeup'] },
            { word: 'Slugging', taboo: ['Vaseline', 'Petroleum', 'Overnight', 'Seal', 'Moisture'] },
            { word: 'Glass Skin', taboo: ['Korean', 'Glowing', 'Clear', 'Dewy', 'Smooth'] },
            { word: 'Skin Barrier', taboo: ['Protect', 'Damage', 'Repair', 'Moisture', 'Layer'] },
            { word: 'Chemical Peel', taboo: ['Acid', 'Exfoliate', 'Remove', 'Layer', 'Renew'] },
            { word: 'Dermatologist', taboo: ['Doctor', 'Skin', 'Specialist', 'Medical', 'Prescription'] },
            { word: 'Collagen', taboo: ['Protein', 'Firm', 'Elasticity', 'Aging', 'Plump'] },
            { word: 'AHA', taboo: ['Glycolic', 'Lactic', 'Acid', 'Exfoliate', 'Chemical'] },
            { word: 'BHA', taboo: ['Salicylic', 'Acid', 'Pores', 'Oil', 'Acne'] },
            { word: 'Ceramides', taboo: ['Barrier', 'Lipids', 'Moisture', 'Repair', 'CeraVe'] },
            { word: 'SPF', taboo: ['Sun', 'Protection', 'Factor', 'Number', 'Sunscreen'] },
            { word: 'Gua Sha', taboo: ['Stone', 'Massage', 'Face', 'Sculpt', 'Chinese'] }
        ]
    },

    california: {
        id: 'california',
        name: 'California',
        icon: '🌴',
        cards: [
            { word: 'Golden Gate Bridge', taboo: ['San Francisco', 'Red', 'Bridge', 'Bay', 'Fog'] },
            { word: 'Hollywood Sign', taboo: ['Los Angeles', 'Letters', 'Hills', 'Movies', 'White'] },
            { word: 'Disneyland', taboo: ['Anaheim', 'Mickey', 'Theme Park', 'Castle', 'Magic'] },
            { word: 'Silicon Valley', taboo: ['Tech', 'Apple', 'Google', 'Computers', 'Startups'] },
            { word: 'In-N-Out', taboo: ['Burger', 'Fast Food', 'Animal Style', 'Double Double', 'Fries'] },
            { word: 'Yosemite', taboo: ['National Park', 'Waterfall', 'El Capitan', 'Half Dome', 'Valley'] },
            { word: 'Beverly Hills', taboo: ['Rich', 'Famous', 'LA', 'Mansion', '90210'] },
            { word: 'San Diego', taboo: ['Zoo', 'Beach', 'Navy', 'South', 'Whale'] },
            { word: 'Napa Valley', taboo: ['Wine', 'Grapes', 'Vineyard', 'Tasting', 'North'] },
            { word: 'Venice Beach', taboo: ['Boardwalk', 'Muscle', 'Skate', 'LA', 'Ocean'] },
            { word: 'Lake Tahoe', taboo: ['Ski', 'Snow', 'Nevada', 'Blue', 'Mountain'] },
            { word: 'Alcatraz', taboo: ['Prison', 'Island', 'San Francisco', 'Escape', 'Rock'] },
            { word: 'Joshua Tree', taboo: ['Desert', 'National Park', 'Cactus', 'U2', 'Rocks'] },
            { word: 'Rodeo Drive', taboo: ['Shopping', 'Expensive', 'Beverly Hills', 'Luxury', 'Stores'] },
            { word: 'Pacific Coast Highway', taboo: ['Road', 'Ocean', 'Drive', 'PCH', 'One'] },
            { word: 'Coachella', taboo: ['Music', 'Festival', 'Desert', 'April', 'Palm Springs'] },
            { word: 'Santa Monica Pier', taboo: ['Beach', 'Ferris Wheel', 'LA', 'Ocean', 'Boardwalk'] },
            { word: 'Big Sur', taboo: ['Coast', 'Cliffs', 'Highway', 'Beautiful', 'Drive'] },
            { word: 'Death Valley', taboo: ['Hot', 'Desert', 'National Park', 'Below Sea Level', 'Temperature'] },
            { word: 'Fisherman\'s Wharf', taboo: ['San Francisco', 'Seafood', 'Sea Lions', 'Pier', 'Clam Chowder'] },
            { word: 'UC Berkeley', taboo: ['University', 'College', 'Campus', 'Cal', 'Bay Area'] },
            { word: 'Stanford', taboo: ['University', 'College', 'Palo Alto', 'Cardinal', 'Campus'] },
            { word: 'Redwood Forest', taboo: ['Trees', 'Tall', 'Giant', 'Sequoia', 'National Park'] },
            { word: 'Sacramento', taboo: ['Capital', 'Government', 'Kings', 'River', 'State'] },
            { word: 'Malibu', taboo: ['Beach', 'Surf', 'Celebrities', 'Coast', 'Pacific'] },
            { word: 'Cable Cars', taboo: ['San Francisco', 'Trolley', 'Hills', 'Ride', 'Street'] },
            { word: 'Getty Museum', taboo: ['Art', 'LA', 'Free', 'Gardens', 'Views'] },
            { word: 'Griffith Observatory', taboo: ['LA', 'Stars', 'Hollywood', 'View', 'Planetarium'] },
            { word: 'Earthquake', taboo: ['Shake', 'Fault', 'San Andreas', 'Richter', 'Ground'] },
            { word: 'Avocado Toast', taboo: ['Brunch', 'Trendy', 'Millennial', 'Food', 'Green'] }
        ]
    },

    pittsburgh: {
        id: 'pittsburgh',
        name: 'Pittsburgh',
        icon: '🌉',
        cards: [
            { word: 'Steelers', taboo: ['Football', 'Black', 'Yellow', 'NFL', 'Terrible Towel'] },
            { word: 'Penguins', taboo: ['Hockey', 'Ice', 'Sidney Crosby', 'NHL', 'Stanley Cup'] },
            { word: 'Pirates', taboo: ['Baseball', 'PNC Park', 'MLB', 'Buccos', 'Roberto Clemente'] },
            { word: 'Primanti Brothers', taboo: ['Sandwich', 'Fries', 'Coleslaw', 'Bread', 'Restaurant'] },
            { word: 'Heinz Field', taboo: ['Stadium', 'Steelers', 'Football', 'Ketchup', 'North Shore'] },
            { word: 'Three Rivers', taboo: ['Ohio', 'Allegheny', 'Monongahela', 'Water', 'Confluence'] },
            { word: 'Point State Park', taboo: ['Fountain', 'Downtown', 'Rivers', 'Triangle', 'Point'] },
            { word: 'Incline', taboo: ['Duquesne', 'Monongahela', 'Hill', 'Trolley', 'View'] },
            { word: 'Strip District', taboo: ['Market', 'Food', 'Shopping', 'Neighborhood', 'Penn Avenue'] },
            { word: 'Carnegie Museums', taboo: ['Art', 'Natural History', 'Dinosaur', 'Oakland', 'Andrew'] },
            { word: 'University of Pittsburgh', taboo: ['Pitt', 'Cathedral', 'Learning', 'Oakland', 'Panthers'] },
            { word: 'Carnegie Mellon', taboo: ['University', 'College', 'Tech', 'Robots', 'Oakland'] },
            { word: 'Kennywood', taboo: ['Amusement Park', 'Rides', 'Coaster', 'Potato Patch', 'Summer'] },
            { word: 'Yinzer', taboo: ['Pittsburgh', 'Accent', 'Local', 'Slang', 'You Ones'] },
            { word: 'Jagoff', taboo: ['Pittsburgh', 'Insult', 'Slang', 'Jerk', 'Yinzer'] },
            { word: 'Pierogies', taboo: ['Polish', 'Dumpling', 'Potato', 'Food', 'Mrs. T\'s'] },
            { word: 'Terrible Towel', taboo: ['Steelers', 'Yellow', 'Wave', 'Football', 'Fan'] },
            { word: 'Andy Warhol', taboo: ['Artist', 'Pop Art', 'Museum', 'Soup Cans', 'Famous'] },
            { word: 'PNC Park', taboo: ['Baseball', 'Pirates', 'Stadium', 'River', 'Bridge'] },
            { word: 'PPG Place', taboo: ['Glass', 'Building', 'Downtown', 'Ice Rink', 'Tower'] },
            { word: 'Shadyside', taboo: ['Neighborhood', 'Shopping', 'Walnut Street', 'East End', 'Trendy'] },
            { word: 'Squirrel Hill', taboo: ['Neighborhood', 'Jewish', 'Murray Avenue', 'East', 'Diverse'] },
            { word: 'South Side', taboo: ['Bars', 'Carson Street', 'Neighborhood', 'Nightlife', 'Slopes'] },
            { word: 'Bridges', taboo: ['Three', 'Yellow', 'Rivers', 'Cross', '446'] },
            { word: 'Steel City', taboo: ['Pittsburgh', 'Nickname', 'Industry', 'Metal', 'Mills'] },
            { word: 'Roberto Clemente', taboo: ['Pirates', 'Baseball', 'Bridge', '21', 'Puerto Rico'] },
            { word: 'Phipps Conservatory', taboo: ['Greenhouse', 'Plants', 'Flowers', 'Oakland', 'Garden'] },
            { word: 'Mount Washington', taboo: ['View', 'Incline', 'Hill', 'Overlook', 'South'] },
            { word: 'Franco Harris', taboo: ['Steelers', 'Football', 'Immaculate Reception', 'Running Back', '32'] },
            { word: 'Iron City Beer', taboo: ['Pittsburgh', 'Brewery', 'Local', 'IC Light', 'Drink'] }
        ]
    },

    madison: {
        id: 'madison',
        name: 'Madison',
        icon: '🏛️',
        cards: [
            { word: 'State Capitol', taboo: ['Building', 'Dome', 'Government', 'White', 'Square'] },
            { word: 'UW Madison', taboo: ['University', 'Wisconsin', 'Badgers', 'College', 'Campus'] },
            { word: 'Camp Randall', taboo: ['Stadium', 'Football', 'Badgers', 'Jump Around', 'Sports'] },
            { word: 'State Street', taboo: ['Downtown', 'Shopping', 'Bars', 'Capitol', 'Walk'] },
            { word: 'Badgers', taboo: ['Wisconsin', 'UW', 'Red', 'Sports', 'Football'] },
            { word: 'Cheese Curds', taboo: ['Fried', 'Wisconsin', 'Squeaky', 'Dairy', 'Snack'] },
            { word: 'Lake Mendota', taboo: ['Water', 'UW', 'Terrace', 'Sailing', 'Madison'] },
            { word: 'Lake Monona', taboo: ['Water', 'Capitol', 'East Side', 'Isthmus', 'Madison'] },
            { word: 'Memorial Union Terrace', taboo: ['Lake', 'Chairs', 'Beer', 'Sunset', 'UW'] },
            { word: 'Isthmus', taboo: ['Land', 'Lakes', 'Narrow', 'Between', 'Downtown'] },
            { word: 'Bucky Badger', taboo: ['Mascot', 'Wisconsin', 'UW', 'Red', 'Animal'] },
            { word: 'Dane County', taboo: ['Madison', 'County', 'Farmers Market', 'Government', 'Wisconsin'] },
            { word: 'Farmers Market', taboo: ['Capitol Square', 'Saturday', 'Vegetables', 'Cheese', 'Local'] },
            { word: 'Willy Street', taboo: ['Neighborhood', 'Coop', 'East Side', 'Hippie', 'Alternative'] },
            { word: 'Epic Systems', taboo: ['Healthcare', 'Software', 'Verona', 'Company', 'Tech'] },
            { word: 'Olbrich Gardens', taboo: ['Flowers', 'Thai Pavilion', 'Botanical', 'Free', 'Park'] },
            { word: 'Henry Vilas Zoo', taboo: ['Animals', 'Free', 'Kids', 'Park', 'Lions'] },
            { word: 'Spotted Cow', taboo: ['Beer', 'New Glarus', 'Wisconsin', 'Brewery', 'Local'] },
            { word: 'Jump Around', taboo: ['Camp Randall', 'Song', 'Football', 'Badgers', 'Fourth Quarter'] },
            { word: 'Bascom Hill', taboo: ['UW', 'Steep', 'Lincoln', 'Campus', 'Walk'] },
            { word: 'Monona Terrace', taboo: ['Frank Lloyd Wright', 'Convention', 'Lake', 'Building', 'Downtown'] },
            { word: 'Great Dane', taboo: ['Brewpub', 'Beer', 'Restaurant', 'Local', 'Capitol'] },
            { word: 'Bratfest', taboo: ['Sausage', 'Memorial Day', 'Festival', 'World\'s Largest', 'Food'] },
            { word: 'Overture Center', taboo: ['Arts', 'Theater', 'Music', 'Downtown', 'Performance'] },
            { word: 'Chazen Museum', taboo: ['Art', 'Free', 'UW', 'Campus', 'Gallery'] },
            { word: 'Devil\'s Lake', taboo: ['State Park', 'Bluffs', 'Swimming', 'Hiking', 'Baraboo'] },
            { word: 'Ian\'s Pizza', taboo: ['Slice', 'Mac and Cheese', 'State Street', 'Late Night', 'Drunk'] },
            { word: 'Middleton', taboo: ['Suburb', 'Best Place', 'Capital Brewery', 'West', 'Greenway'] },
            { word: 'Arboretum', taboo: ['UW', 'Nature', 'Trees', 'Hiking', 'Prairie'] },
            { word: 'On Wisconsin', taboo: ['Fight Song', 'Badgers', 'UW', 'Football', 'Music'] }
        ]
    },

    chicago: {
        id: 'chicago',
        name: 'Chicago',
        icon: '🏙️',
        cards: [
            { word: 'Willis Tower', taboo: ['Sears', 'Tall', 'Skyscraper', 'Skydeck', 'Building'] },
            { word: 'Cloud Gate', taboo: ['Bean', 'Mirror', 'Sculpture', 'Millennium Park', 'Silver'] },
            { word: 'Navy Pier', taboo: ['Ferris Wheel', 'Lake', 'Tourist', 'Pier', 'Fireworks'] },
            { word: 'Deep Dish Pizza', taboo: ['Chicago', 'Thick', 'Cheese', 'Lou Malnati\'s', 'Giordano\'s'] },
            { word: 'Cubs', taboo: ['Baseball', 'Wrigley', 'North Side', 'MLB', 'Curse'] },
            { word: 'White Sox', taboo: ['Baseball', 'South Side', 'MLB', 'Guaranteed Rate', 'AL'] },
            { word: 'Bears', taboo: ['Football', 'NFL', 'Soldier Field', 'Da Bears', 'Monsters'] },
            { word: 'Bulls', taboo: ['Basketball', 'Jordan', 'NBA', 'United Center', 'Red'] },
            { word: 'Blackhawks', taboo: ['Hockey', 'NHL', 'Stanley Cup', 'Indian', 'Ice'] },
            { word: 'Wrigley Field', taboo: ['Cubs', 'Baseball', 'Ivy', 'Stadium', 'North Side'] },
            { word: 'Magnificent Mile', taboo: ['Shopping', 'Michigan Avenue', 'Stores', 'Luxury', 'Downtown'] },
            { word: 'Lake Michigan', taboo: ['Water', 'Great Lake', 'Beach', 'Shore', 'Lake Shore Drive'] },
            { word: 'L Train', taboo: ['Elevated', 'CTA', 'Subway', 'Loop', 'Transportation'] },
            { word: 'Italian Beef', taboo: ['Sandwich', 'Meat', 'Dipped', 'Giardiniera', 'Hot'] },
            { word: 'Chicago Hot Dog', taboo: ['No Ketchup', 'Mustard', 'Relish', 'Sport Pepper', 'Vienna'] },
            { word: 'Portillo\'s', taboo: ['Hot Dog', 'Italian Beef', 'Fast Food', 'Restaurant', 'Cake Shake'] },
            { word: 'Garrett Popcorn', taboo: ['Chicago Mix', 'Caramel', 'Cheese', 'Snack', 'Tin'] },
            { word: 'Second City', taboo: ['Comedy', 'Improv', 'SNL', 'Theater', 'Funny'] },
            { word: 'Art Institute', taboo: ['Museum', 'Lions', 'Paintings', 'Grant Park', 'Art'] },
            { word: 'Field Museum', taboo: ['Sue', 'Dinosaur', 'Natural History', 'Science', 'Museum'] },
            { word: 'Shedd Aquarium', taboo: ['Fish', 'Museum', 'Lake Shore', 'Animals', 'Water'] },
            { word: 'Lollapalooza', taboo: ['Music', 'Festival', 'Grant Park', 'Summer', 'Concert'] },
            { word: 'River Walk', taboo: ['Downtown', 'Water', 'Restaurants', 'Walk', 'Boats'] },
            { word: 'Lincoln Park', taboo: ['Zoo', 'Neighborhood', 'North Side', 'Park', 'Free'] },
            { word: 'Buckingham Fountain', taboo: ['Grant Park', 'Water', 'Lights', 'Married with Children', 'Pink'] },
            { word: 'Al Capone', taboo: ['Gangster', 'Mafia', 'Prohibition', 'Crime', 'Scarface'] },
            { word: 'Michael Jordan', taboo: ['Bulls', 'Basketball', '23', 'GOAT', 'Nike'] },
            { word: 'O\'Hare', taboo: ['Airport', 'Fly', 'ORD', 'International', 'Terminal'] },
            { word: 'Sears', taboo: ['Tower', 'Willis', 'Department Store', 'Building', 'Tall'] },
            { word: 'Windy City', taboo: ['Chicago', 'Nickname', 'Wind', 'Lake', 'Cold'] }
        ]
    },

    newyork: {
        id: 'newyork',
        name: 'New York',
        icon: '🗽',
        cards: [
            { word: 'Statue of Liberty', taboo: ['Ellis Island', 'Torch', 'Green', 'France', 'Freedom'] },
            { word: 'Times Square', taboo: ['Billboards', 'Broadway', 'New Year', 'Lights', 'Midtown'] },
            { word: 'Central Park', taboo: ['Manhattan', 'Green', 'Joggers', 'Trees', 'Zoo'] },
            { word: 'Empire State Building', taboo: ['Tall', 'Skyscraper', 'King Kong', 'Observation', 'Art Deco'] },
            { word: 'Brooklyn Bridge', taboo: ['Walk', 'East River', 'Brooklyn', 'Manhattan', 'Suspension'] },
            { word: 'Wall Street', taboo: ['Stock', 'Money', 'Finance', 'Bull', 'Banks'] },
            { word: 'Broadway', taboo: ['Theater', 'Musical', 'Shows', 'Times Square', 'Stage'] },
            { word: 'Subway', taboo: ['Train', 'Underground', 'MTA', 'Commute', 'Metro'] },
            { word: 'Yankees', taboo: ['Baseball', 'Bronx', 'Pinstripes', 'MLB', 'Stadium'] },
            { word: 'Mets', taboo: ['Baseball', 'Queens', 'Citi Field', 'MLB', 'Amazing'] },
            { word: 'Knicks', taboo: ['Basketball', 'MSG', 'NBA', 'Madison Square Garden', 'Orange'] },
            { word: 'Pizza', taboo: ['Slice', 'Fold', 'Dollar', 'New York Style', 'Cheese'] },
            { word: 'Bagel', taboo: ['Round', 'Cream Cheese', 'Lox', 'Deli', 'Breakfast'] },
            { word: 'Bodega', taboo: ['Corner Store', 'Deli', 'Cat', 'Sandwich', 'Grocery'] },
            { word: 'Fifth Avenue', taboo: ['Shopping', 'Luxury', 'Stores', 'Trump Tower', 'Fancy'] },
            { word: 'Grand Central', taboo: ['Train', 'Station', 'Terminal', 'Clock', 'Commuter'] },
            { word: 'SoHo', taboo: ['Shopping', 'Neighborhood', 'Art', 'Lofts', 'South of Houston'] },
            { word: 'Brooklyn', taboo: ['Borough', 'Bridge', 'Hipster', 'Williamsburg', 'Kings'] },
            { word: 'Manhattan', taboo: ['Island', 'Borough', 'Skyscrapers', 'NYC', 'Midtown'] },
            { word: 'Queens', taboo: ['Borough', 'Airport', 'Flushing', 'Diverse', 'Mets'] },
            { word: 'Bronx', taboo: ['Borough', 'Yankees', 'Zoo', 'Hip Hop', 'North'] },
            { word: 'Staten Island', taboo: ['Borough', 'Ferry', 'Island', 'Forgotten', 'Bridge'] },
            { word: 'High Line', taboo: ['Park', 'Elevated', 'Train Tracks', 'Walk', 'Chelsea'] },
            { word: 'MOMA', taboo: ['Art', 'Museum', 'Modern', 'Starry Night', 'Gallery'] },
            { word: 'Met', taboo: ['Museum', 'Art', 'Metropolitan', 'Fifth Avenue', 'Gala'] },
            { word: 'Rockefeller Center', taboo: ['Ice Skating', 'Christmas Tree', 'NBC', 'Top of the Rock', '30 Rock'] },
            { word: 'One World Trade', taboo: ['Freedom Tower', 'Tall', '9/11', 'Memorial', 'Downtown'] },
            { word: 'Hamilton', taboo: ['Musical', 'Broadway', 'Lin-Manuel', 'Founding Father', 'Tickets'] },
            { word: 'Yellow Cab', taboo: ['Taxi', 'Drive', 'Medallion', 'Uber', 'Hail'] },
            { word: 'Hot Dog Cart', taboo: ['Street', 'Vendor', 'Food', 'Mustard', 'Pretzel'] }
        ]
    }
};

// Export for use in main game
if (typeof module !== 'undefined' && module.exports) {
    module.exports = DECKS;
}
